import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/authContext";
import { ProfileProvider } from "./context/profileContext";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { SessionProvider } from "./context/SessionContext";
import LinkedListNavigation from "./components/Linkedlist";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
        <AuthProvider>
          <ProfileProvider>
            <Navbar/>
             <LinkedListNavigation/>
            {children}
            <Footer/>
          </ProfileProvider>
            
        </AuthProvider>
        </SessionProvider>
      
      </body>
    </html>
  );
}
